// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.createUserSessionStmt, err = db.PrepareContext(ctx, createUserSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserSession: %w", err)
	}
	if q.deleteUserSessionStmt, err = db.PrepareContext(ctx, deleteUserSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserSession: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.saveVerificationCodeStmt, err = db.PrepareContext(ctx, saveVerificationCode); err != nil {
		return nil, fmt.Errorf("error preparing query SaveVerificationCode: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.createUserSessionStmt != nil {
		if cerr := q.createUserSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserSessionStmt: %w", cerr)
		}
	}
	if q.deleteUserSessionStmt != nil {
		if cerr := q.deleteUserSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserSessionStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.saveVerificationCodeStmt != nil {
		if cerr := q.saveVerificationCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveVerificationCodeStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                       DBTX
	tx                       *sql.Tx
	createUserStmt           *sql.Stmt
	createUserSessionStmt    *sql.Stmt
	deleteUserSessionStmt    *sql.Stmt
	getUserByEmailStmt       *sql.Stmt
	saveVerificationCodeStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                       tx,
		tx:                       tx,
		createUserStmt:           q.createUserStmt,
		createUserSessionStmt:    q.createUserSessionStmt,
		deleteUserSessionStmt:    q.deleteUserSessionStmt,
		getUserByEmailStmt:       q.getUserByEmailStmt,
		saveVerificationCodeStmt: q.saveVerificationCodeStmt,
	}
}
