// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions(user_id)
VALUES ($1)
RETURNING id,user_id,created_at, expires_at
`

func (q *Queries) CreateUserSession(ctx context.Context, userID uuid.UUID) (UserSession, error) {
	row := q.queryRow(ctx, q.createUserSessionStmt, createUserSession, userID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
