// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_codes.sql

package store

import (
	"context"
	"time"
)

const saveVerificationCode = `-- name: SaveVerificationCode :one
INSERT INTO verification_codes(user_id,verfication_type,expires_at)
VALUES ($1,$2,$3)
RETURNING user_id,verfication_type, created_at, expires_at
`

type SaveVerificationCodeParams struct {
	UserID          int32     `json:"user_id"`
	VerficationType string    `json:"verfication_type"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) SaveVerificationCode(ctx context.Context, arg SaveVerificationCodeParams) (VerificationCode, error) {
	row := q.queryRow(ctx, q.saveVerificationCodeStmt, saveVerificationCode, arg.UserID, arg.VerficationType, arg.ExpiresAt)
	var i VerificationCode
	err := row.Scan(
		&i.UserID,
		&i.VerficationType,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
